### ISSUE TITLE
Network via websock VPN

### ISSUE THREAD

**Issue by h4x3rotab** [jaromaz/jslinux-mobile#2]
The original JSLinux has websocket VPN support. I wonder if it can be implemented here. It's an interesting idea is to run a special browser with built-in VPN on iOS so that the emulator can connect to external server by SSH.

**Comment by jaromaz** [comment]
This requires VPS infrastructure - as long as the iOS version does not bring any money, it will not be possible here :) 
This version of the emulator is created mainly for educational purposes, but maybe someone will do a fork and create such a websock version.

**Comment by jaromaz** [comment]
@h4x3rotab @ewiger
Maybe this solution will do the job? :)
https://github.com/ewiger/jsmodem
